# Join debain host to windows domain

- hosts: ubuntu-clients
  gather_facts: no
  remote_user: root

  vars:
    team_number: "{{ team | default('01') }}"

  tasks:
    - name: Update hostname
      shell: |
        hostnamectl set-hostname {{ machine_name }}


    - name: Set dns-search config
      lineinfile:
        name: /etc/network/interfaces
        line: ' dns-search {{ team_number }}.wildeagle.local'

    - name: Set nameservers config
      lineinfile:
        name: /etc/network/interfaces
        line: ' dns-nameservers 10.1.{{ team_number }}.10'

 
    - name: Set resolv nameservers config
      lineinfile:
        name: /etc/resolv.conf
        line: 'nameserver 10.1.{{ team_number }}.10'

 
    - name: Set resolv search config
      lineinfile:
        name: /etc/resolv.conf
        line: 'search team{{ team_number }}.wildeagle.local'


    - name: Restart network services
      shell: |
        systemctl restart networking.service
        apt -y install ntpdate
        ntpdate -q team{{ team_number }}.wildeagle.local
 

    - name: Update and install packages
      shell: |
         apt -y install winbind samba cifs-utils smbclient libpam-winbind libnss-winbinf
         apt -y install krb5config krb5-user

    - name: Push SMB config
      blockinfile:
        block: "{{ lookup('file', '../scripts/smb.conf') }}"
        dest: "/etc/samba/smb.conf"
        backup: yes

    - name: Fix team number
      shell:
         sed -i 's/TEAMXX/TEAM{{ team_number }}/g' /etc/samba/smb.conf

    - name: Restart service
      shell: |
        systemctl restart smbd nmdb winbind
        net ads join -U Administrator
        pam-auth-update
        sed -i 's/passwd.*/passwd: compat winbind/g' /etc/nsswitch.conf
        sed -i 's/group.*/group:   compat winbind/g' /etc/nsswitch.conf
        sed -i 's/shadow.*/shadow:  compat winbind/g' /etc/nsswitch.conf
        echo "session required	pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-account
        service smbd restart
        service winbind restart


